language: node_js
node_js:
  - "12"

before_script:
  - cd client/

script:
  - npm install
  - npm run build
  - echo "Finished building"

deploy:
  on:
    provider: script
    skip_cleanup: true
    script: echo "About to deploy!"
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false

branches:
  only:
    - master