language: node_js
node_js:
  - "12"

before_script:
  - cd client/

cache:
  directories:
    - client/node_modules

script:
  - npm install
  - npm run build
  - echo "Finished building"

deploy:
  provider: script
  skip_cleanup: true
  script: echo "About to deploy!"
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false

branches:
  only:
    - master